server:
  port: 8081


spring:
  application:
    name: spring-cloud-config-client
  config:
    import: "optional:configserver:http://localhost:8888"


management:
  endpoints:
    web:
      exposure:
        include: "refresh,env,health,info"